### ISSUE TITLE
在crystal页面上往存储策略中添加设备后，查看builder文件报错

### ISSUE THREAD

**Issue by xietiangui** [OStorage/crystal-controller#1]
在crystal页面上往存储策略中添加设备后，查看builder文件报错，报错信息如下：
```
Traceback (most recent call last):
  File "/usr/bin/swift-ring-builder", line 24, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/swift/cli/ringbuilder.py", line 1483, in main
    getattr(Commands, command, Commands.unknown)()
  File "/usr/lib/python2.7/site-packages/swift/cli/ringbuilder.py", line 527, in default
    print_dev_f(dev, balance_per_dev[dev['id']], flags)
  File "/usr/lib/python2.7/site-packages/swift/cli/ringbuilder.py", line 423, in print_dev_f
    print(format_string % args)
TypeError: %d format: a number is required, not str

**Comment by xietiangui** [comment]
相关的代码已提交:[代码提交链接](https://github.com/OStorage/crystal-controller/pull/2/files)

**Comment by xietiangui** [comment]
在添加设备时，如果在crystal的页面中添加的region和zone是英文的话，也会出现报错
